language: node_js
node_js:
  - 12
branches:
  except:
    - /^no-ci.*$/
services:
  - xvfb
# before_install:
#     - sudo apt-get update -qq;
#       sudo apt-get install -y --no-install-recommends libcairo2-dev build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
# before_install:
#   - if [ $TRAVIS_OS_NAME == linux ]; then
#       sudo apt-get update -qq;
#       sudo apt-get install -y --no-install-recommends libxrandr-dev libxi-dev libxxf86vm-dev libsdl2-dev;
#       wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip;
#       unzip glfw-3.2.1.zip && cd glfw-3.2.1;
#       cmake -DBUILD_SHARED_LIBS=true -DGLFW_BUILD_EXAMPLES=false -DGLFW_BUILD_TESTS=false -DGLFW_BUILD_DOCS=false .;
#       sudo make -j $CPU_NUM install && cd ..;
#     fi
script:
  - yarn run test-coveralls
  - yarn run typecheck
