#!/bin/bash

# Bundles py-slang's py2js engine into vendor/py2js-bundle.cjs, which the Python
# grader loads at runtime.
#
# By default this clones py-slang ($PY_SLANG_REPO at $PY_SLANG_REF). Set
# $PY_SLANG_DIR to bundle from an existing local checkout instead.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
outfile="$repo_root/vendor/py2js-bundle.cjs"

PY_SLANG_REPO="${PY_SLANG_REPO:-https://github.com/source-academy/py-slang}"
PY_SLANG_REF="${PY_SLANG_REF:-main}"

# Clone into a temp dir unless a local checkout is provided; clean it up on exit.
cloned_dir=""
cleanup() { [ -n "$cloned_dir" ] && rm -rf "$cloned_dir"; }
trap cleanup EXIT

if [ -n "${PY_SLANG_DIR:-}" ]; then
  py_slang_dir="$(cd "$PY_SLANG_DIR" && pwd)"
else
  cloned_dir="$(mktemp -d)"
  echo "Cloning $PY_SLANG_REPO @ $PY_SLANG_REF ..."
  git clone --depth 1 --branch "$PY_SLANG_REF" "$PY_SLANG_REPO" "$cloned_dir"
  py_slang_dir="$cloned_dir"
fi

entry="$py_slang_dir/src/engines/py2js/index.ts"
if [ ! -f "$entry" ]; then
  echo "py-slang engine entry not found at $entry (set PY_SLANG_DIR or PY_SLANG_REF)." >&2
  exit 1
fi

# Install py-slang's own dependencies so esbuild can resolve its imports.
if [ ! -d "$py_slang_dir/node_modules" ]; then
  echo "Installing py-slang dependencies in $py_slang_dir ..."
  (cd "$py_slang_dir" && corepack yarn install --immutable)
fi

py_slang_ref="$(git -C "$py_slang_dir" rev-parse HEAD 2>/dev/null || echo unknown)"

mkdir -p "$(dirname "$outfile")"

esbuild_bin="$py_slang_dir/node_modules/.bin/esbuild"
if [ ! -x "$esbuild_bin" ]; then
  echo "esbuild not found at $esbuild_bin (expected from py-slang's dependencies)." >&2
  exit 1
fi

"$esbuild_bin" "$entry" \
  --bundle \
  --platform=node \
  --format=cjs \
  --target=node22 \
  --outfile="$outfile" \
  --loader:.wasm=binary \
  --legal-comments=none \
  --banner:js="// GENERATED by scripts/build-py2js-bundle.sh - DO NOT EDIT.
// @sourceacademy/py-slang src/engines/py2js/index.ts @ $py_slang_ref"

echo "Wrote vendor/$(basename "$outfile") (py-slang ${py_slang_ref:0:12})"
