#!/bin/bash

# Bundles py-slang's py2js engine into vendor/py2js-bundle.cjs, which the Python
# grader loads at runtime. Point PY_SLANG_DIR at a py-slang checkout to override
# the default sibling directory.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
py_slang_dir="$(cd "${PY_SLANG_DIR:-$repo_root/../source-academy-py-slang}" 2>/dev/null && pwd || true)"
entry="$py_slang_dir/src/engines/py2js/index.ts"
outfile="$repo_root/vendor/py2js-bundle.cjs"

if [ ! -f "$entry" ]; then
  echo "py-slang engine entry not found at ${entry:-$py_slang_dir/src/engines/py2js/index.ts} (set PY_SLANG_DIR)." >&2
  exit 1
fi

py_slang_ref="$(git -C "$py_slang_dir" rev-parse HEAD 2>/dev/null || echo unknown)"

mkdir -p "$(dirname "$outfile")"

# py-slang's source tree has no node_modules; resolve its bare imports from ours.
NODE_PATH="$repo_root/node_modules" "$repo_root/node_modules/.bin/esbuild" "$entry" \
  --bundle \
  --platform=node \
  --format=cjs \
  --target=node22 \
  --outfile="$outfile" \
  --loader:.wasm=binary \
  --legal-comments=none \
  --banner:js="// GENERATED by scripts/build-py2js-bundle.sh - DO NOT EDIT.
// @sourceacademy/py-slang src/engines/py2js/index.ts @ $py_slang_ref"

echo "Wrote vendor/$(basename "$outfile") (py-slang ${py_slang_ref:0:12})"
