name: Build layer
on: workflow_dispatch

jobs:
  xvfb:
    name: Build Xvfb
    runs-on: ubuntu-latest
    container: amazon/aws-lambda-nodejs:16
    steps:
      - uses: actions/checkout@v3
      - name: Build Xvfb
        run: scripts/build-lambda-xvfb.sh
      - uses: actions/upload-artifact@v3
        with:
          name: xvfbzip
          path: /opt/xvfb.zip
          if-no-files-found: error
