name: Build layer
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  xvfb:
    name: Build Xvfb
    runs-on: ubuntu-latest
    container: amazon/aws-lambda-nodejs:24-x86_64
    steps:
      - name: install git and tar
        run: yum install -y git tar bzip2 zip
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Xvfb
        run: scripts/build-lambda-xvfb.sh
      - uses: actions/upload-artifact@v4
        with:
          name: xvfbzip
          path: /opt/xvfb.zip
          if-no-files-found: error
