name: Build Lambda function
on: workflow_dispatch

jobs:
  tsc:
    name: Compile TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - name: Compile TypeScript
        run: scripts/build-lambda-grader.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build-lambda
          path: build.tar.bz2
          if-no-files-found: error
  native:
    name: Build native modules
    needs: tsc
    runs-on: ubuntu-latest
    container: amazon/aws-lambda-nodejs:16.x
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: build-lambda
      - name: Rebuild native modules
        run: scripts/build-lambda-grader-in-docker.sh
      - uses: actions/upload-artifact@v2
        with:
          name: graderzip
          path: grader.zip
          if-no-files-found: error
      - uses: geekyeggo/delete-artifact@v1
        with:
          failOnError: false
          name: build-lambda
